### ISSUE TITLE
Index error after passing action to site packages

### ISSUE THREAD

**Issue by mericdemirors** [k4ntz/HackAtari#7]
Below is the trace:

Traceback (most recent call last):
  File ",,,/run.py", line 65, in <module>
    env.run()
  File ",,,/hackatari/core.py", line 253, in run
    _, reward, _, _, _ =self.step(action)
  File ",,,/hackatari/core.py", line 126, in _alter_step
    obs, reward, terminated, truncated, info = self._env.step(*args, **kwargs)
  File ".../python3.10/site-packages/gymnasium/wrappers/common.py", line 393, in step
    return super().step(action)
  File ".../python3.10/site-packages/gymnasium/core.py", line 322, in step
    return self.env.step(action)
  File ".../python3.10/site-packages/gymnasium/wrappers/common.py", line 285, in step
    return self.env.step(action)
  File ".../python3.10/site-packages/ale_py/env.py", line 293, in step
    action_idx = self._action_set[action]
IndexError: list index out of range

I solved the issue by fixing some codes in ".../lib/python3.10/site-packages/ale_py/env.py, line 293"
This is the working "else block" for me:
        else:
            if isinstance(action, int):
                action_idx = self._action_set[action]
                strength = 1.0
            else:
                action_idx = action
                strength = 1.0

Issue was this: "action" is an int variable when idle, but "class Action" object which (I guess) acts as an int when any key pressed. While running the "self._action_set[action]" line, the object "<Action.LEFT; 4>" is passed to an array with length of 4 so it gives an error. It is trying to retrieve an action called "Action.LEFT", by an index (which is for the list of whole possible actions on all games [.../lib/python3.10/site-packages/ale_py/__init__.pyi line 82]) on a list of 'actions that are used in this game', so it misses some of the actions (for example no Action.UP in Breakout game) so the indexing gets messed up/shifted.
When it is trying to retrieve the action by passing its int value as index, it retrieves wrong action or goes beyond the bounds. But no need to get the action by its int value since we already got the action itself in the "action" variable when key pressed.
Don't know(also care) if it is related to HackAtari, gymnasium or ale_py. Just wanted to post the fix for it if there are other people struggling with it.

**Comment by btw04** [comment]
#6 also fixes this issue by forcing the action space for any HumanPlayable environment to include all actions, without needing to modify ALE
